# Default labels

- color: d73a4a
  name: bug
  description: Something isn't working
- color: cfd3d7
  name: duplicate
  description: This issue or pull request already exists
- color: a2eeef
  name: enhancement
  description: New feature or request
- color: 008672
  name: help wanted
  description: Extra attention is needed
- color: d876e3
  name: question
  description: Further information is requested

# Own labels

- color: '072540'
  name: hacktoberfest
  description: Not too heavy to lift. A nice thing for newcommers.
- color: '072540'
  name: hacktoberfest-accepted
  description: This PR will count towards your hacktoberfest score, even if not merged.
- color: ffffff
  name: stale
  description: No interactions for quite some time
- color: 3e2487
  name: dependency-update
  description: Updates a dependency
- color: ffe2b3
  name: invalid-template
  description: This issue does not use one of the provided templates.

# Addon labels

- color: 039dfc
  name: ICantBelieveItsNotValetudo
  description: ICantBelieveItsNotValetudo Addon
- color: 039dfc
  name: MaryTTS
  description: MaryTTS Addon
- color: 039dfc
  name: OWASP-ZAP
  description: OWASP-ZAP Addon
- color: 039dfc
  name: container-stats
  description: container-stats Addon
- color: 039dfc
  name: git-exporter
  description: git-exporter Addon
- color: 039dfc
  name: mitmproxy
  description: mitmproxy Addon
- color: 039dfc
  name: mpd
  description: mpd Addon
- color: 039dfc
  name: picoTTS
  description: picoTTS Addon
- color: 039dfc
  name: pigpio
  description: pigpio Addon
- color: 039dfc
  name: rsync
  description: rsync Addon
- color: 039dfc
  name: rsync-local
  description: rsync-local Addon
- color: 039dfc
  name: syncthing
  description: syncthing Addon
- color: 039dfc
  name: valetudo-mapper
  description: valetudo-mapper Addon
- color: 039dfc
  name: vnc-viewer
  description: vnc-viewer Addon
- color: 039dfc
  name: ympd
  description: ympd Addon
- color: 039dfc
  name: mopidy
  description: mopidy Addon
- color: 039dfc
  name: asterisk
  description: Asterisk Addon
- color: 039dfc
  name: juice-shop
  description: OWASP Juice Shop
- color: 039dfc
  name: pixelflut
  description: Pixelflut
