name: pigpio
version: 1.5.3-migrate
slug: pigpio
description: 🚨 Addons are moved to https://github.com/Poeschl-HomeAssistant-Addons/repository
url: https://github.com/Poeschl/Hassio-Addons/tree/main/pigpio
arch:
  - armhf
  - armv7
  - aarch64
startup: services
gpio: true
privileged:
  - SYS_RAWIO
devices:
  - /dev/mem
  - /dev/vcio
image: ghcr.io/poeschl-homeassistant-addons/pigpio-{arch}
init: false
ports:
  8888/tcp: 8888
ports_description:
  8888/tcp: The port to control pigpio
schema:
  additional_options: str?
homeassistant_api: true
