name: MaryTTS
version: 1.5.2-migrate
slug: marytts
description: 🚨 Addons are moved to https://github.com/Poeschl-HomeAssistant-Addons/repository
url: https://github.com/Poeschl/Hassio-Addons/tree/main/MaryTTS
webui: http://[HOST]:[PORT:59125]
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: ghcr.io/poeschl-homeassistant-addons/marytts-{arch}
init: false
ports:
  59125/tcp: 59125
ports_description:
  59125/tcp: Port to access MaryTTS
options:
  language: en
schema:
  language: list(de|en|fr|it|in|tu|lu)
  voice: match(^https?://.+\.zip)?
homeassistant_api: true
